batch_size: 4
config_path: /home/merci/PycharmProjects/competitions/HuBMAP/config/runs/dataset_image.yaml
data_path: /home/merci/PycharmProjects/competitions/HuBMAP/data/hubmap-hacking-the-human-vasculature/train
num_workers: 8
random_state: 42
target_path: /home/merci/PycharmProjects/competitions/HuBMAP/data/hubmap-hacking-the-human-vasculature/polygons.jsonl
train_size: 0.8
